{{
    config(
        materialized='incremental',
        database='TRACKING_PORTAFOLIO',
        schema='STG_SOURCE',
        pre_hook="TRUNCATE TABLE IF EXISTS {{ this }}"
    )
}}

SELECT
    $1:ACCOUNTID::VARCHAR as ACCOUNTID,
    $1:SYMBOL::VARCHAR as SYMBOL,
    $1:DESCRIPTION::VARCHAR as DESCRIPTION,
    $1:EXCHANGE::VARCHAR as EXCHANGE,
    TO_DATE($1:REPORT_DATE::VARCHAR, 'DD/MM/YYYY') as REPORT_DATE,
    $1:QUANTITY::NUMBER as QUANTITY,
    REPLACE(REPLACE($1:COST_BASE::VARCHAR, '.', ''), ',', '.')::NUMBER as COST_BASE,
    REPLACE(REPLACE($1:POSITION_VALUE::VARCHAR, '.', ''), ',', '.')::NUMBER as POSITION_VALUE,
    $1:CURRENCY::VARCHAR as CURRENCY,
    REPLACE(REPLACE($1:UNREALIZED_PROFIT::VARCHAR, '.', ''), ',', '.')::NUMBER as UNREALIZED_PROFIT,
    REPLACE(REPLACE($1:UNREALIZED_PROFIT_PCT::VARCHAR, ',', '.'), '%', '')::NUMBER as UNREALIZED_PROFIT_PCT
FROM @TRACKING_PORTAFOLIO.STG_SOURCE.STG_RAW/archivo.json
(FILE_FORMAT => TRACKING_PORTAFOLIO.STG_SOURCE.JSON_FORMAT)