{{
    config(
        materialized='incremental',
        database='TRACKING_PORTAFOLIO',
        pre_hook="TRUNCATE TABLE IF EXISTS {{ this }}"
    )
}}



WITH DATE_FINAL AS (
    SELECT 
        ACCOUNTID
        , DATEADD( DAY, -1, DATEADD( MONTH, 1, DATE_TRUNC( 'MONTH', REPORT_DATE))) AS REPORT_DATE_MONTH
        , CURRENCY
        , CURRENCY_DESCRIPTION
        , ROUND( SUM (COST_BASE_LC), 3) AS COST_LC
        , ROUND( SUM ( POSITION_VALUE_LC), 3) AS POSICION_LC
        , ROUND( SUM (COST_BASE_EURO), 3) AS COST_EURO
        , ROUND( SUM ( POSITION_VALUE_EURO), 3) AS POSICION_EURO
        , ROUND( SUM (COST_BASE_USD), 3) AS COST_USD
        , ROUND( SUM ( POSITION_VALUE_USD), 3) AS POSICION_USD
    FROM {{ ref('PSA_SLV_POSITION_TRANSFORMATIONS') }}
    GROUP BY 
         ACCOUNTID
        , DATEADD( DAY, -1, DATEADD( MONTH, 1, DATE_TRUNC( 'MONTH', REPORT_DATE))) 
        , CURRENCY
        , CURRENCY_DESCRIPTION
)
SELECT 
    ACCOUNTID
    , REPORT_DATE_MONTH
    , CURRENCY
    , CURRENCY_DESCRIPTION
    , COST_LC
    , POSICION_LC
    , SUM( COST_LC) OVER( PARTITION BY ACCOUNTID ORDER BY REPORT_DATE_MONTH ASC, CURRENCY ) AS COST_LC_ACUMULATED
    , SUM( POSICION_LC) OVER( PARTITION BY ACCOUNTID ORDER BY REPORT_DATE_MONTH ASC, CURRENCY ) AS POSITION_LC_ACUMULATED
    , COST_EURO
    , POSICION_EURO
    , SUM( COST_EURO) OVER( PARTITION BY ACCOUNTID ORDER BY REPORT_DATE_MONTH ASC, CURRENCY ) AS COST_EURO_ACUMULATED
    , SUM( POSICION_EURO) OVER( PARTITION BY ACCOUNTID ORDER BY REPORT_DATE_MONTH ASC, CURRENCY ) AS POSICION_EURO_ACUMULATED
    , COST_USD
    , POSICION_USD
    , SUM( COST_USD) OVER( PARTITION BY ACCOUNTID ORDER BY REPORT_DATE_MONTH ASC, CURRENCY ) AS COST_USD_ACUMULATED
    , SUM( POSICION_USD) OVER( PARTITION BY ACCOUNTID ORDER BY REPORT_DATE_MONTH ASC, CURRENCY ) AS POSICION_USD_ACUMULATED

 FROM DATE_FINAL
 ORDER BY 
    ACCOUNTID
    , REPORT_DATE_MONTH
    , CURRENCY
    

