
SELECT 
    ACCOUNTID
    , MONTH( REPORT_DATE) AS MONTH_NUMBER
    , DESCRIPTION
    , CURRENCY
    , CURRENCY_DESCRIPTION
    , SUM (COST_BASE_LC) AS COST_LC
    , SUM ( POSITION_VALUE_LC) AS POSICION_LC
    , SUM (COST_BASE_EURO) AS COST_EURO
    , SUM ( POSITION_VALUE_EURO) AS POSICION_EURO
    , SUM (COST_BASE_USD) AS COST_USD
    , SUM ( POSITION_VALUE_USD) AS POSICION_USD

FROM {{ ref('PSA_SLV_POSITION_TRANSFORMATIONS') }} 
GROUP BY 
    ACCOUNTID
    , MONTH( REPORT_DATE) 
    , DESCRIPTION
    , CURRENCY
    , CURRENCY_DESCRIPTION