


SELECT
    T.ACCOUNTID
    , T.SYMBOL
    , T.DESCRIPTION
    , T.EXCHANGE
    , T.REPORT_DATE
    , T.QUANTITY
    , T.COST_BASE
    , T.POSITION_VALUE
    , T.CURRENCY
    , C.CURRENCY_DESCRIPTION
    , C.EURO
    , C.EURO_TO_LC
    , C.USD
    , ( CASE WHEN T.CURRENCY IN ('EUR', 'XOF') THEN T.POSITION_VALUE
                ELSE ( T.POSITION_VALUE / NULLIF(C.EURO, 0))  END) POSITION_VALUE_EURO
    , ( CASE WHEN T.CURRENCY IN ('USD') THEN T.POSITION_VALUE
                ELSE ( T.POSITION_VALUE / NULLIF(C.USD, 0))  END) POSITION_VALUE_USD
    , ( CASE WHEN T.CURRENCY IN ('EUR', 'XOF') THEN T.COST_BASE
                ELSE ( T.COST_BASE / NULLIF(C.EURO, 0))  END) COST_VALUE_EURO
    , ( CASE WHEN T.CURRENCY IN ('USD') THEN T.COST_BASE
                ELSE ( T.COST_BASE / NULLIF(C.USD, 0))  END) COST_VALUE_USD
    , GETDATE() AS DATE_CURRENTLY
    , EXTRACT( 'dayofweek', REPORT_Date) AS WEEKDAY_
FROM {{ source('snowflake_dbt', 'ABC_BANK_POSITION') }} T 
INNER JOIN {{ source('snowflake_dbt', 'CATALOG_CURRENCY') }} C 
ON T.CURRENCY = C.CURRENCY