
/* Query for perofrming the indicators */

SELECT 
    ACCOUNTID
    , SYMBOL
    , DESCRIPTION
    , EXCHANGE
    , REPORT_DATE
    , QUANTITY
    , CURRENCY
    , CURRENCY_DESCRIPTION
    , EURO
    , EURO_TO_LC
    , USD
    , ROUND( COST_BASE, 3) AS COST_BASE_LC
    , ROUND( POSITION_VALUE, 3) AS POSITION_VALUE_LC
    , ROUND( COST_VALUE_EURO, 3) AS COST_BASE_EURO
    , ROUND( POSITION_VALUE_EURO, 3) AS POSITION_VALUE_EURO
    , ROUND( COST_VALUE_USD, 3) AS COST_BASE_USD
    , ROUND( POSITION_VALUE_USD, 3) AS POSITION_VALUE_USD

    , ROUND( POSITION_VALUE - COST_BASE , 3) as UNREALIZED_PROFIT_LC
    , ROUND((POSITION_VALUE - COST_BASE) / COST_BASE, 3) as UNREALIZED_PROFIT_PCT_LC

    , ROUND( POSITION_VALUE_EURO - COST_VALUE_EURO , 3) as UNREALIZED_PROFIT_EURO
    , ROUND((POSITION_VALUE_EURO - COST_VALUE_EURO) / COST_VALUE_EURO, 3) as UNREALIZED_PROFIT_PCT_EURO

    , ROUND( POSITION_VALUE_USD - COST_VALUE_USD, 3) as UNREALIZED_PROFIT_USD
    , ROUND( POSITION_VALUE_USD - COST_VALUE_USD, 3) as UNREALIZED_PROFIT_PCT_USD
    , DATEDIFF( DAY, REPORT_DATE, DATE_CURRENTLY ) AS DAYS_OPERATION
    , WEEKDAY_
FROM {{ ref('POSITION_ABC_BANK') }} 


-- LIMIT 100