
SELECT
    *
    , POSITION_VALUE - COST_BASE as UNREALIZED_PROFIT
    , ROUND((POSITION_VALUE - COST_BASE) / COST_BASE, 3) as UNREALIZED_PROFIT_PCT
FROM {{ source('snowflake_dbt', 'ABC_BANK_POSITION') }}